version: '3.4'

services:
  attempt.minio:
    image: ${DOCKER_REGISTRY-}attemptminio
    build:
      context: .
      dockerfile: Dockerfile
  minio:
    restart: always
    image: minio/minio
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: 5712F0D8-2F81-4D20-8BC3-6743999DEAD5
      MINIO_SECRET_KEY: 242B166D-A8F0-4475-9366-48CA240AE943
    command: server /export
    volumes:
      - /e/docker_volume/minio/data:/export
      - /e/docker_volume/minio/config:/root/.minio